version: '3.3'


services:
  nnuNetv1:
    image: anilyerramasu/nnunetv1_models_2d_gpu
    ports:
      - 5000:5000
    volumes:
      - ./input:/home/input
      - ./output:/home/output
      - $(pwd)/nnUNet_results:/home/nnUNet/data/models
    # deploy:
    #   resources:
    #   reservations:
    #     generic_resources:
    #       - discrete_resource_spec:
    #         kind: 'NVIDIA-GPU'
    #         value: 0
